chirper/urls.py
"""
chirper/urls.py

Authors: Silas Curtis, Tytus Woodburn
Emails: silas.curtis@student.cune.edu tytus.woodburn@student.cune.edu
Github: https://github.com/tywood01 https://github.com/SilasEC

Purpose:
    Provide view responses for the chirper app.

"""

from django.urls import path
from .views import profile
from . import views

app_name = "chirper"
urlpatterns = [
    path("", views.chirps, name="chirps"),
    path("profile/<str:username>/", profile, name="profile"),
    path("update_profile/", views.update_profile, name="update_profile"),
    path("profile/", views.my_profile, name="my_profile"),
    path("addchirp/", views.add_chirp, name="add_chirp"),
    path("add/<int:parent_id>/", views.add_chirp, name="reply_chirp"),
    path("chirp/<int:chirp_id>/like/", views.toggle_like, name="toggle_like"),
    path("toggle_follow/<str:followed>/", views.toggle_follow, name="toggle_follow"),
]

conf/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("chirper/", include("chirper.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path(
        "accounts/profile/",
        RedirectView.as_view(url="/chirper/profile", permanent=True),
    ),
    path("", RedirectView.as_view(url="/chirper/", permanent=True)),
]

chirper/models.py
"""
models.py

Authors: Silas Curtis, Tytus Woodburn
Emails: silas.curtis@student.cune.edu tytus.woodburn@student.cune.edu
Github: https://github.com/tywood01 https://github.com/SilasEC

Purpose:
    Define the models for the chirper app.
    These will be mapped to the database by Django's ORM.

"""

from django.contrib.auth.models import User
from django.db import models


class Chirp(models.Model):
    """Represents a short message (chirp) in the Chirper app."""

    body = models.CharField(max_length=255)
    date = models.DateTimeField("Created At", auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    parent = models.ForeignKey(
        "chirper.Chirp", on_delete=models.CASCADE, blank=True, null=True
    )


class Profile(models.Model):
    """Represents a user's profile and content about them."""

    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    bio = models.CharField(max_length=255)
    public = models.BooleanField(default=True)


class Likes(models.Model):
    """Represents a user liking a post."""

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    chirp = models.ForeignKey(Chirp, on_delete=models.CASCADE, related_name="likes")

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("user", "chirp"), name="unique user chirp like"
            )
        ]


class Follow(models.Model):
    """Represents a user following another user."""

    follower = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="following"
    )
    followed = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="followers"
    )

    class Meta:
        """One can't follow oneself."""

        constraints = [
            models.UniqueConstraint(
                fields=("follower", "followed"), name="unique follower followed"
            )
        ]

chirper/forms/forms.py
"""
forms.py

Authors: Tytus Woodburn
Email: tytus.woodburn@student.cune.edu
Github: https://github.com/tywood01

Purpose:
    Define reusable forms for the chirper app.

"""

from django import forms
from chirper.models import Chirp, Profile


class ChirpForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.instance.user = request.user

    class Meta:
        model = Chirp
        fields = ["body"]
        widgets = {
            "body": forms.Textarea(
                attrs={
                    "rows": 3,
                    "cols": 60,
                    "placeholder": "What's on your mind, bird brain?",
                    "maxlength": 255,
                }
            ),
        }


class ProfileForm(forms.ModelForm):
    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.instance.user = request.user

    class Meta:
        model = Profile
        fields = ["bio", "public"]

        widgets = {
            "bio": forms.Textarea(
                attrs={
                    "rows": 3,
                    "cols": 60,
                    "placeholder": "Tell us a lil about your bird-self!",
                    "maxlength": 255,
                }
            ),
            "public": forms.CheckboxInput(),
        }

chirper/views.py
"""
views.py

Authors: Silas Curtis, Tytus Woodburn
Emails: silas.curtis@student.cune.edu tytus.woodburn@student.cune.edu
Github: https://github.com/tywood01 https://github.com/SilasEC

Purpose:
    Provide view responses for the chirper app.

"""

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from chirper.models import Chirp, Profile, Likes, Follow
from django.urls import reverse
from chirper.forms.forms import ChirpForm, ProfileForm
from django.http import HttpResponse


def profile(request, username):
    """
    Display a user's profile page showing their information, chirps, and follow status.

    Retrieves the specified user's profile and associated chirps, determines if the
    current user is following them, and renders the profile template with this data.
    """

    template_name = "chirper/profile.html"
    user = get_object_or_404(User, username=username)
    profile, created = Profile.objects.get_or_create(
        user=user,
        defaults={"bio": "Default bio"},
    )

    chirps = Chirp.objects.filter(user=user).order_by("-date")
    is_following = False

    if request.user.is_authenticated:
        is_following = Follow.objects.filter(
            follower=request.user, followed=user
        ).exists()

    context = {
        "profile": profile,
        "user_chirp_list": chirps,
        "user": user,
        "is_following": is_following,
    }
    return render(request, template_name, context)


def my_profile(request):
    """Redirects to logged in user's profile page."""

    if not request.user.is_authenticated:
        return redirect("/accounts/login/")

    return profile(request, username=request.user.username)


@login_required
def update_profile(request):
    """Show an interface for the user to edit their profile."""

    profile = get_object_or_404(Profile, user=request.user)

    if request.method == "POST":
        form = ProfileForm(request, request.POST, instance=profile)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("chirper:my_profile"))

    else:
        form = ProfileForm(request, instance=profile)

    return render(request, "chirper/update_profile.html", {"form": form})


def chirps(request):
    """Print all chirps for user's viewing pleasure."""

    template_name = "chirper/index.html"
    chirp_list = Chirp.objects.all().order_by("-date")

    context = {
        "chirp_list": chirp_list,
        "chirp_likes": {chirp.id: chirp.likes.count() for chirp in chirp_list},
    }

    return render(request, template_name, context)


@login_required
def add_chirp(request, parent_id=None):
    """Create a chirp from logged in user with content from form."""

    if request.method == "POST":
        form = ChirpForm(request, request.POST)

        if form.is_valid():
            chirp = form.save(commit=False)
            chirp.user = request.user

            if parent_id:
                chirp.parent_id = parent_id

            chirp.save()
            return HttpResponseRedirect(reverse("chirper:chirps"))

    else:
        form = ChirpForm(request, initial={"parent": parent_id})

    # If GET request or form invalid, show the form
    return render(request, "chirper/create_chirp.html", {"form": form})


@login_required
def toggle_like(request, chirp_id):
    """Likes or unlikes a chirp based on whether the logged in user already follows them."""

    chirp = get_object_or_404(Chirp, id=chirp_id)
    like, created = Likes.objects.get_or_create(user=request.user, chirp=chirp)

    if not created:
        like.delete()

    # Fetch updated like count from the Likes model
    like_count = Likes.objects.filter(chirp=chirp).count()

    return HttpResponse(f'''
        <button 
            hx-post="{request.path}" 
            hx-swap="outerHTML"
            class="like-button">
            👍 {like_count}
        </button>
    ''')


@login_required
def toggle_follow(request, followed):
    """Follows or unfollows an account based on whether the logged in user already follows them."""

    user = get_object_or_404(User, username=followed)
    follow, created = Follow.objects.get_or_create(follower=request.user, followed=user)

    if not created:
        follow.delete()

    return redirect(reverse("chirper:chirps"))  # Or redirect to profile

chirper/templates/chirper/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        {% block title %}
        Chirper
        {% endblock %}
    </title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    {% block extra_head %}
    {% endblock %}
</head>

<body>
    <header class="header">
        <div class="header__logo-title">
            <div class="header__logo"></div>
            <div class="header__title">
                {% block logo_text %}
                {% endblock %}
            </div>
        </div>
    </header>
    <main class="main">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="footer">
        <p class="footer__text">2025 Chirper Project. :)</p>
    </footer>
</body>

</html>

chirper/templates/chirper/create_chirp.html
{% extends 'chirper/base.html' %}

{% block title %}
Chirper
{% endblock %}

{% block logo_text %}
<h1>Chirp Away</h1>
{% endblock %}

{% block content %}
<main class="main">
    <a href="{% url 'chirper:chirps' %}" class="chirp-form__button">Home</a>
    <a href="{% url 'chirper:my_profile' %}" class="chirp-form__button">My Profile</a>

    <div class="chirp-form">
        <h2>Add a New Chirp</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="chirp-form__button" type="submit">Create Chirp</button>
        </form>
    </div>
</main>
{% endblock %}

chirper/templates/chirper/index.html
{% extends 'chirper/base.html' %}

{% block title %}
Chirper
{% endblock %}

{% block logo_text %}
<h1>Chirper</h1>
{% endblock %}

{% block content %}
<main class="main">
    <a href="{% url 'chirper:add_chirp' %}" class="chirp-form__button">Add Chirp</a>
    <a href="{% url 'chirper:my_profile' %}" class="chirp-form__button">My Profile</a>

    <br><br>

    {% if chirp_list %}
    <ul>
        {% for chirp in chirp_list %}
        <div class="post">
            <div class="chirp-form__user-info">
                <div class="chirp-form__avatar"></div>

                <div class="post__content-text">
                    <h3>Chirp by <a href="{% url 'chirper:profile' username=chirp.user %}">{{ chirp.user }}</a></h3>
                    <p>{{ chirp.body }}</p>
                    {% if chirp.likes.count == 1 %}
                    <p>{{ chirp.likes.count }} Like</p>
                    {% else %}
                    <p>{{ chirp.likes.count }} likes</p>
                    {% endif %}
                    <small>{{ chirp.date }}</small>
                </div>
            </div>
            {% if request.user.is_authenticated %}
            <form action="{% url 'chirper:toggle_like' chirp_id=chirp.id %}" method="post">
                {% csrf_token %}
                {% if request.user in chirp.likes.all %}
                <button class="post__like-btn" type="submit">Unlike</button>
                {% else %}
                <button class="post__like-btn" type="submit">Like</button>
                {% endif %}
            </form>
            {% endif %}

            <form action="{% url 'chirper:reply_chirp' chirp.id %}" method="get">
                <button class="chirp-form__button" type="submit">Reply</button>
            </form>
        </div>
        {% endfor %}
    </ul>
    {% else %}
    <p>No chirps available.</p>
    {% endif %}
</main>
{% endblock %}

chirper/templates/chirper/profile.html
{% extends 'chirper/base.html' %}

{% block title %}
Chirper
{% endblock %}

{% block logo_text %}
<h1>Profile</h1>
{% endblock %}

{% block content %}
<main class="main">
    <a href="{% url 'chirper:chirps' %}" class="chirp-form__button">Home</a>
    <a href="{% url 'chirper:add_chirp' %}" class="chirp-form__button">Add Chirp</a>

    <h1>{{ user.username }}</h1>
    <p>Bio: {{ profile.bio }}</p>

    {% if request.user.is_authenticated %}
    <form action="{% url 'chirper:toggle_follow' followed=user.username %}" method="post">
        {% csrf_token %}
        {% if is_following %}
        <button class="chirp-form__button" type="submit">Unfollow</button>
        {% else %}
        <button class="chirp-form__button" type="submit">Follow</button>
        {% endif %}
    </form>
    {% endif %}

    {% if request.user.is_authenticated and user == request.user %}
    <form action="{% url 'chirper:update_profile' %}" method="get">
        <button class="chirp-form__button" type="submit">Update Profile</button>
    </form>
    {% endif %}

    {% if user_chirp_list %}
    <ul>
        {% for chirp in user_chirp_list %}
        <li class="post">
            <p>{{ chirp.body }}</p>
            <small>Posted on: {{ chirp.date }}</small>
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>No chirps available.</p>
    {% endif %}
</main>
{% endblock %}

chirper/templates/chirper/update_profile.html
{% extends 'chirper/base.html' %}

{% block title %}
Profile
{% endblock %}

{% block logo_text %}
<h1>Update</h1>
{% endblock %}

{% block content %}
<main class="main">
    <a href="{% url 'chirper:chirps' %}" class="chirp-form__button">Home</a>
    <a href="{% url 'chirper:my_profile' %}" class="chirp-form__button">My Profile</a>

    <div class="chirp-form">
        <h2>Update Profile</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="chirp-form__button" type="submit">Update</button>
        </form>
    </div>
</main>
{% endblock %}